export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const LOAD_SEATS_SUCCESS = 'LOAD_SEATS_SUCCESS';
export const SELECT_SEAT_SUCCESS = 'SELECT_SEAT_SUCCESS';
export const DESELECT_SEAT_SUCCESS = 'DESELECT_SEAT_SUCCESS';
export const MARK_SEAT_SOLD_SUCCESS = 'MARK_SEAT_SOLD_SUCCESS';
